"""initial_schema

Revision ID: 4a66a17abb57
Revises: 
Create Date: 2026-05-03 10:16:41.567413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a66a17abb57'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column(
        'plan',
        sa.Enum('free', 'pro', 'enterprise', name='user_plan', native_enum=False, length=32),
        nullable=False,
        server_default=sa.text("'free'"),
    ),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clerk_id'), 'users', ['clerk_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('apps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column(
        'platform',
        sa.Enum('google_play', 'app_store', 'both', name='app_platform', native_enum=False, length=32),
        nullable=False,
    ),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('bundle_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('icon_url', sa.String(length=2048), nullable=True),
    sa.Column('developer', sa.String(length=512), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apps_user_id'), 'apps', ['user_id'], unique=False)
    op.create_table('review_fetches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column(
        'status',
        sa.Enum('pending', 'running', 'completed', 'failed', name='fetch_status', native_enum=False, length=32),
        nullable=False,
        server_default=sa.text("'pending'"),
    ),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_fetches_app_id'), 'review_fetches', ['app_id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.Column(
        'type',
        sa.Enum('heuristic', 'ai', name='analysis_type', native_enum=False, length=32),
        nullable=False,
    ),
    sa.Column(
        'status',
        sa.Enum('pending', 'running', 'completed', 'failed', name='analysis_status', native_enum=False, length=32),
        nullable=False,
        server_default=sa.text("'pending'"),
    ),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_used', sa.String(length=128), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fetch_id'], ['review_fetches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_app_id'), 'analyses', ['app_id'], unique=False)
    op.create_index(op.f('ix_analyses_fetch_id'), 'analyses', ['fetch_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.Column('store_review_id', sa.String(length=255), nullable=False),
    sa.Column(
        'platform',
        sa.Enum('google_play', 'app_store', name='review_platform', native_enum=False, length=32),
        nullable=False,
    ),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=512), nullable=True),
    sa.Column('lang', sa.String(length=16), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('thumbs_up', sa.Integer(), nullable=False),
    sa.Column('developer_reply', sa.Text(), nullable=True),
    sa.Column('reply_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_reviews_rating_range'),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fetch_id'], ['review_fetches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'store_review_id', name='uq_reviews_platform_store_id')
    )
    op.create_index(op.f('ix_reviews_app_id'), 'reviews', ['app_id'], unique=False)
    op.create_index(op.f('ix_reviews_fetch_id'), 'reviews', ['fetch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_fetch_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_app_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_analyses_fetch_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_app_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_review_fetches_app_id'), table_name='review_fetches')
    op.drop_table('review_fetches')
    op.drop_index(op.f('ix_apps_user_id'), table_name='apps')
    op.drop_table('apps')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
